version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api.dockerfile
    env_file:
      - ./env/api.env
    volumes:
      - ./api:/app
    depends_on:
      - mysql

  # app:

  mysql:
    image: mysql
    env_file:
      - ./env/mysql.env

  # npm:
