version: "3.8"

services:
  # App container configurations
  api:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api.dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./env/api.env
    volumes:
      - ./api:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

  app:
    build:
      context: ./app
      dockerfile: ../dockerfiles/app.dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./env/app.env
    volumes:
      - ./app:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # Utility containers
  npm:
    build:
      context: ./app
      dockerfile: ../dockerfiles/npm.dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    entrypoint: [ "npm" ]

  django:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api.dockerfile
    env_file:
      - ./env/api.env
    volumes:
      - ./api:/app
    entrypoint: [ "python", "manage.py" ]

  # Use for running django unit tests with sqlite db
  django-test:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api.dockerfile
    env_file:
      - ./env/test-api.env
    volumes:
      - ./api:/app
    entrypoint: [ "python", "manage.py", "test", "--settings", "api.test_settings" ]
