version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api.dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./env/api.env
    volumes:
      - ./api:/app
    depends_on:
      - mysql
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

  # app:

  mysql:
    image: mysql:8
    env_file:
      - ./env/mysql.env
    command: --default-authentication-plugin=mysql_native_password

  # npm:
