interface TDQuoteData {
  assetType: string,
  assetMainType: string,
  cusip: string,
  symbol: string,
  description: string,
  bidPrice: number,
  bidSize: number,
  bidId: string,
  askPrice: number,
  askSize: number,
  askId: string,
  lastPrice: number,
  lastSize: number,
  lastId: string,
  openPrice: number,
  highPrice: number,
  lowPrice: number,
  bidTick: string,
  closePrice: number,
  netChange: number,
  totalVolume: number,
  quoteTimeInLong: number,
  tradeTimeInLong: number,
  mark: number,
  exchange: string,
  exchangeName: string,
  volatility: number,
  digits: number,
  peRatio: number,
  divAmount: number,
  divYield: number,
  divDate: string,
  delayed: boolean,
  realtimeEntitled: boolean
}

export default TDQuoteData;
